repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-unit-tests
      - id: go-build
      - id: golangci-lint

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.15.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      # - id: detect-aws-credentials
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: aligo
        name: aligo
        entry: scripts/aligo.sh
        language: script
        types: [go]

  - repo: local
    hooks:
      - id: staticcheck
        name: staticcheck
        entry: scripts/staticcheck.sh
        language: script
        types: [go]

  - repo: local
    hooks:
      - id: gosec
        name: gosec
        entry: scripts/gosec.sh
        language: script
        types: [go]

  - repo: local
    hooks:
      - id: Govulncheck
        name: Govulncheck
        entry: scripts/govulncheck.sh
        language: script
        types: [go]

  - repo: local
    hooks:
      - id: depcheck
        name: depcheck
        entry: scripts/depcheck.sh
        language: script
        types: [go]

  - repo: local
    hooks:
      - id: go-coverage
        name: go-coverage
        entry: scripts/go-coverage.sh
        language: script
        types: [go]

  - repo: local
    hooks:
      - id: golint
        name: golint
        entry: scripts/golint.sh
        language: script
        types: [go]

  - repo: local
    hooks:
      - id: goimports-reviser
        name: goimports-reviser
        entry: scripts/goimports-reviser.sh
        language: script
        types: [go]

  - repo: local
    hooks:
      - id: gocyclo
        name: gocyclo
        entry: scripts/gocyclo.sh
        language: script
        types: [go]

  - repo: local
    hooks:
      - id: go-duplication
        name: go-duplication
        entry: scripts/go-duplication.sh
        language: script
        types: [go]
